#!/usr/bin/env python3
"""
Deterministic briefing composer.

The daily briefing used to be generated by a local Mistral-7B via MLX. That
made every morning run slow (model load) and occasionally wrong: fed many UMM
facts, the model padded the text far past the popover fold and misread planned
outage windows as permanent shutdowns. Everything the briefing needs to say is
derivable from the aggregator payload, so it is composed from templates
instead: instant, locale-correct (Swedish decimal commas), and it cannot
hallucinate. The MLX model still powers the chat (chat.py), where open-ended
interpretation earns its latency.

The briefing is capped at four sentences plus the recommendation, in priority
order: price level and daily shape, nuclear outages (or an honest "unknown"
when the plugin failed), upcoming outages (aggregated to ONE sentence),
tomorrow's direction, wind. Whatever doesn't fit the cap is dropped — the
cards below the text carry the detail.
"""
import json
import sys
from pathlib import Path

MAX_SENTENCES = 4   # excluding the appended recommendation

_MONTHS_SV = ["januari", "februari", "mars", "april", "maj", "juni",
              "juli", "augusti", "september", "oktober", "november", "december"]
_MONTHS_EN = ["January", "February", "March", "April", "May", "June",
              "July", "August", "September", "October", "November", "December"]


def _fmt(value: float, sv: bool, decimals: int = 0) -> str:
    """Number for prose — Swedish prose uses a decimal comma."""
    s = f"{value:.{decimals}f}"
    return s.replace(".", ",") if sv else s


def _nice_date(iso: str, sv: bool) -> str:
    """'2026-07-04' -> '4 juli' / 'July 4'. Falls back to the raw string."""
    try:
        _, m, d = iso[:10].split("-")
        month, day = int(m), int(d)
        return f"{day} {_MONTHS_SV[month - 1]}" if sv else f"{_MONTHS_EN[month - 1]} {day}"
    except (ValueError, IndexError):
        return iso


def _time_of_day(hour: int, sv: bool) -> str:
    if hour < 6 or hour >= 22:
        return "natten" if sv else "the night"
    if hour < 10:
        return "morgonen" if sv else "the morning"
    if hour < 12:
        return "förmiddagen" if sv else "late morning"
    if hour < 18:
        return "eftermiddagen" if sv else "the afternoon"
    return "kvällen" if sv else "the evening"


def _price_level(avg: float, sv: bool) -> str:
    if avg < 0:
        return "negativt" if sv else "negative"
    if avg < 15:
        return "mycket lågt" if sv else "very low"
    if avg < 40:
        return "lågt" if sv else "low"
    if avg < 80:
        return "måttligt" if sv else "moderate"
    if avg < 150:
        return "högt" if sv else "high"
    return "mycket högt" if sv else "very high"


def _join_names(names: list[str], sv: bool) -> str:
    if len(names) == 1:
        return names[0]
    conj = " och " if sv else " and "
    return ", ".join(names[:-1]) + conj + names[-1]


def _price_shape_sentence(elpris: dict, core: dict, sv: bool) -> str | None:
    avg = elpris.get("avg_price")
    prices = elpris.get("prices") or []
    if avg is None or not prices:
        return None
    level = _price_level(avg, sv)

    cheap_hour = core.get("cheapest_window_start")
    if cheap_hour is None:
        cheap_hour = min(prices, key=lambda p: p["price_ore_kwh"])["hour"]
    exp_hour = max(prices, key=lambda p: p["price_ore_kwh"])["hour"]

    cheap_tod, exp_tod = _time_of_day(cheap_hour, sv), _time_of_day(exp_hour, sv)
    if cheap_tod == exp_tod:
        return (f"Spotpriset i SE3 är {level} idag och relativt jämnt över dygnet."
                if sv else
                f"The SE3 spot price is {level} today and fairly flat across the day.")
    return (f"Spotpriset i SE3 är {level} idag — billigast under {cheap_tod}, dyrast under {exp_tod}."
            if sv else
            f"The SE3 spot price is {level} today — cheapest during {cheap_tod}, most expensive during {exp_tod}.")


def _nuclear_sentence(reaktor_entry: dict, sv: bool) -> str | None:
    data = reaktor_entry.get("data") or {}
    if reaktor_entry.get("error") or not data:
        # A failed plugin must not read as a quiet grid.
        return ("Kärnkraftens driftläge är okänt – UMM-data kunde inte hämtas."
                if sv else
                "Nuclear outage status is unknown – UMM data could not be fetched.")
    plants = data.get("plants") or []
    if not plants:
        return None
    mw = data.get("total_unavail_mw")
    names = _join_names(plants, sv) if len(plants) <= 3 else (
        f"{len(plants)} reaktorer" if sv else f"{len(plants)} reactors")
    mw_part = ""
    if isinstance(mw, (int, float)) and mw > 0:
        mw_part = f" ({round(mw)} MW borta)" if sv else f" ({round(mw)} MW offline)"
    return (f"{names} står stilla{mw_part}, vilket håller uppe prisnivån."
            if sv else
            f"{names} {'is' if len(plants) == 1 else 'are'} offline{mw_part}, which props up prices.")


def _upcoming_sentence(reaktor_data: dict, sv: bool) -> str | None:
    """All upcoming outages aggregated into ONE sentence — never one per plant."""
    upcoming = reaktor_data.get("upcoming_umms") or []
    plants = reaktor_data.get("upcoming_plants") or []
    if not upcoming or not plants:
        return None
    dated = [(u.get("event_start") or "9999", u.get("plant", "?")) for u in upcoming]
    first_start, first_plant = min(dated)
    when = _nice_date(first_start, sv) if first_start != "9999" else None
    if len(plants) == 1:
        if when:
            return (f"{plants[0]} har ett planerat avbrott från {when}."
                    if sv else f"{plants[0]} has a planned outage starting {when}.")
        return (f"{plants[0]} har ett planerat avbrott framöver."
                if sv else f"{plants[0]} has an upcoming planned outage.")
    n = len(plants)
    if when:
        return (f"{n} reaktorer har planerade avbrott framöver, närmast {first_plant} den {when}."
                if sv else
                f"{n} reactors have planned outages ahead, the first being {first_plant} on {when}.")
    return (f"{n} reaktorer har planerade avbrott framöver."
            if sv else f"{n} reactors have planned outages ahead.")


def _tomorrow_sentence(elpris: dict, sv: bool) -> str | None:
    tomorrow = elpris.get("tomorrow_prices") or []
    avg = elpris.get("avg_price")
    if not tomorrow or avg is None or avg <= 0:
        return None
    t_avg = sum(p["price_ore_kwh"] for p in tomorrow) / len(tomorrow)
    ratio = (t_avg - avg) / avg
    if ratio > 0.15:
        word = "dyrare" if sv else "more expensive"
    elif ratio < -0.15:
        word = "billigare" if sv else "cheaper"
    else:
        word = "ungefär samma prisnivå" if sv else "roughly the same level"
    return (f"Imorgon väntas {word}, snitt cirka {_fmt(t_avg, sv)} öre/kWh."
            if sv else
            f"Tomorrow looks {word}, averaging about {_fmt(t_avg, sv)} öre/kWh.")


def _wind_sentence(vader: dict, sv: bool) -> str | None:
    wind = vader.get("daily_avg_wind_ms")
    if wind is None:
        return None
    if wind >= 6:
        return ("God vind ger hög vindproduktion som pressar priserna."
                if sv else "Strong wind is driving high wind output, pushing prices down.")
    if wind <= 2.5:
        return ("Svag vind ger litet vindkrafttillskott."
                if sv else "Weak wind means little wind power on the grid.")
    return None


def generate_briefing(payload: dict, language: str = "sv") -> str:
    sv = language == "sv"
    plugins = payload.get("plugins", {})
    elpris = (plugins.get("elpris") or {}).get("data") or {}
    core = (plugins.get("core") or {}).get("data") or {}
    reaktor_entry = plugins.get("reaktorstatus") or {}
    vader = (plugins.get("vader") or {}).get("data") or {}

    candidates = [
        _price_shape_sentence(elpris, core, sv),
        _nuclear_sentence(reaktor_entry, sv),
        _upcoming_sentence(reaktor_entry.get("data") or {}, sv),
        _tomorrow_sentence(elpris, sv),
        _wind_sentence(vader, sv),
    ]
    sentences = [s for s in candidates if s][:MAX_SENTENCES]

    if not sentences:
        sentences = ["Dagens elmarknadsdata kunde inte hämtas." if sv
                     else "Today's market data could not be fetched."]

    return (" ".join(sentences) + _recommendation_sentence(payload, language)).strip()


def _recommendation_sentence(payload: dict, language: str = "sv") -> str:
    core = (payload.get("plugins", {}).get("core") or {}).get("data") or {}
    s, e, ca = core.get("cheapest_window_start"), core.get("cheapest_window_end"), core.get("cheapest_window_avg")
    if s is None or e is None or ca is None:
        return ""
    sv = language == "sv"
    return (f" Kör tunga jobb {s:02d}:00–{e:02d}:00 ({_fmt(ca, sv, 1)} öre/kWh)."
            if sv else
            f" Run heavy loads {s:02d}:00–{e:02d}:00 ({_fmt(ca, sv, 1)} öre/kWh).")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        payload = json.loads(Path(sys.argv[1]).read_text())
    else:
        payload = json.load(sys.stdin)

    print(generate_briefing(payload))
